INSERT INTO company_norms (code, description, severity) VALUES
  ('AN01', 'Não responder documentos internos ou respondê-los fora do prazo', 'leve'),
  ('AN02', 'Uso indiscriminado de aparelhos eletrônicos ou outro material que tire a atenção individual ou alheia durante qualquer reunião interna', 'leve'),
  ('AN03', 'Perturbar a paz dentro do ambiente de trabalho', 'leve'),
  ('AN04', 'Chegar após o tempo de tolerância de 15 minutos em qualquer atividade referente à empresa', 'leve'),
  ('AN05', 'Não buscar informar-se das decisões tomadas nas reuniões faltadas', 'leve'),
  ('AN06', 'Desarrumar e não reorganizar o ambiente da sala no seu expediente', 'leve'),
  ('AN07', 'Sair antes do horário previsto em reuniões e/ou não completar atividades ou rotina de sala sem justificativa prévia', 'leve'),
  ('AN08', 'Consumir alimentos dentro do ambiente de trabalho', 'leve'),
  ('AN09', 'Utilizar vestimentas inadequadas no ambiente de trabalho', 'leve'),
  ('AN10', 'Linguagem inapropriada/ofensiva ou difamação ao companheiro no ambiente de trabalho', 'moderada'),
  ('AN11', 'Não comparecer a alguma atividade referente à empresa com justificativas não aceitas, ou não justificadas', 'moderada'),
  ('AN12', 'Fazer mal-uso de todo material e espaço físico pertencente à empresa', 'moderada'),
  ('AN13', 'Não cumprir a rotina de sala sem justificativa prévia', 'moderada'),
  ('AN14', 'Retirar ou liberar a retirada de material da empresa e não comunicar aos responsáveis pelo controle desses materiais', 'moderada'),
  ('AN15', 'Não entregar tarefa por irresponsabilidade ou entregá-la malfeita', 'moderada'),
  ('AN16', 'Faltas em reuniões gerais e setoriais', 'moderada'),
  ('AN17', 'Falsificar assinaturas em atas de qualquer evento relacionado à Watt', 'grave'),
  ('AN18', 'Atrapalhar, intencionalmente ou por irresponsabilidade, de alguma forma a realização das atividades da empresa', 'grave'),
  ('AN19', 'Se atrasar mais que 15 minutos em compromissos com clientes e parceiros da Watt', 'grave'),
  ('AN20', 'Desrespeitar a hierarquia da empresa', 'grave'),
  ('AN21', 'Utilizar o uniforme da empresa para realizar atividades pessoais que possam de alguma forma denegrir a imagem da mesma, mediante prova', 'grave'),
  ('AN22', 'Utilizar uniforme inapropriado em visitas presenciais ao cliente', 'grave'),
  ('AN23', 'Compartilhar documentos da empresa com não membros sem autorização da diretoria', 'desligamento'),
  ('AN24', 'Mentir ou omitir (comprovadamente) para a diretoria para ganhar tempo, vantagem ou evitar punição', 'desligamento'),
  ('AN25', 'Assédio de qualquer natureza com um companheiro de trabalho', 'desligamento'),
  ('AN26', 'Atrapalhar intencionalmente de alguma forma a realização das atividades da empresa', 'desligamento'),
  ('AN27', 'Discriminar pessoas por cor/raça, etnia, sexo, idade, origem regional, condição econômica, social, condição física ou mental, orientação política, religiosa ou sexual ou por qualquer outra condição', 'desligamento'),
  ('AN28', 'Trabalhar sob efeito de álcool ou drogas ilícitas', 'desligamento'),
  ('AN29', 'Furtar material da empresa (inclui dinheiro)', 'desligamento'),
  ('AN30', 'Agredir fisicamente qualquer indivíduo quando estiver em serviço ou dentro do ambiente da empresa', 'desligamento'),
  ('AN31', 'Abandonar um projeto em andamento', 'desligamento');
